export type DataDrivenElement = Record<string, unknown>;
export * from "./schema/enchantment/AttributeEffectFields.ts";
export * from "./schema/enchantment/ConditionalEffect.ts";
export * from "./schema/enchantment/EffectComponents.ts";
export * from "./schema/enchantment/Enchantment.ts";
export * from "./schema/enchantment/EnchantmentCost.ts";
export * from "./schema/enchantment/EnchantmentEntityEffect.ts";
export * from "./schema/enchantment/EnchantmentLocationEffect.ts";
export * from "./schema/enchantment/EnchantmentValueEffect.ts";
export * from "./schema/enchantment/LevelBasedValue.ts";
export * from "./schema/enchantment/ParticlePositionSource.ts";
export * from "./schema/enchantment/ParticleVelocitySource.ts";
export * from "./schema/enchantment/SharedEffects.ts";
export * from "./schema/enchantment/SoundValue.ts";
export * from "./schema/enchantment/TargetedConditionalEffect.ts";
export * from "./schema/tag/TagType.ts";
export * from "./schema/text/TextComponentType.ts";
